# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JlHhnLcBF1VvRbtMUUBsR2JIUJTHVQ5a
"""

# decision_tree_classifier.py

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef
from sklearn.tree import DecisionTreeClassifier

train_df = pd.read_csv("Train_Data.csv")
test_df = pd.read_csv("Test_Data.csv")

train_df = train_df.drop(columns=["#", "Name"], errors='ignore')
test_df = test_df.drop(columns=["#", "Name"], errors='ignore')

X_train = pd.get_dummies(train_df.drop("Legendary", axis=1), drop_first=True)
X_test = pd.get_dummies(test_df.drop("Legendary", axis=1), drop_first=True)
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

y_train = train_df["Legendary"].astype(bool)
y_test = test_df["Legendary"].astype(bool)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("Decision Tree Results")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_prob))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("MCC:", matthews_corrcoef(y_test, y_pred))